definitions:
  demo.loginRequest:
    properties:
      user_id:
        description: 用户ID（>0）
        type: integer
      user_name:
        description: 用户名
        type: string
    type: object
  demo.loginResponse:
    properties:
      authorization:
        description: 签名
        type: string
    type: object
host: 127.0.0.1:9999
info:
  contact: {}
  title: go-gin-api docs api
paths:
  /demo/user/{name}:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      parameters:
      - description: 用户名(Tom)
        in: path
        name: name
        required: true
        type: string
      - description: 签名
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            items:
              properties:
                job:
                  description: 工作
                  type: string
                name:
                  description: 用户名
                  type: string
              type: object
            type: array
      summary: 获取用户信息
      tags:
      - Demo
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录获取 Authorization 码
      parameters:
      - description: 请求信息
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/demo.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 签名信息
          schema:
            $ref: '#/definitions/demo.loginResponse'
      summary: 登录获取 Authorization 码
      tags:
      - Demo
swagger: "2.0"
