definitions:
  code.Failure:
    properties:
      code:
        description: 业务码
        type: integer
      message:
        description: 描述信息
        type: string
    type: object
  demo.authResponse:
    properties:
      authorization:
        description: 签名
        type: string
      expire_time:
        description: 过期时间
        type: integer
    type: object
  user_model.CreateRequest:
    properties:
      mobile:
        description: 手机号
        type: string
      nick_name:
        description: 昵称
        type: string
      user_name:
        description: 用户名
        type: string
    type: object
  user_model.CreateResponse:
    properties:
      id:
        description: 主键ID
        type: integer
    type: object
  user_model.DetailResponse:
    properties:
      id:
        description: 用户主键ID
        type: integer
      mobile:
        description: 手机号（脱敏）
        type: string
      nick_name:
        description: 昵称
        type: string
      user_name:
        description: 用户名
        type: string
    type: object
  user_model.UpdateNickNameByIDRequest:
    properties:
      id:
        description: 用户主键ID
        type: integer
      nick_name:
        description: 昵称
        type: string
    type: object
  user_model.UpdateNickNameByIDResponse:
    properties:
      id:
        description: 用户主键ID
        type: integer
    type: object
host: 127.0.0.1:9999
info:
  contact: {}
  license:
    name: MIT
    url: https://github.com/xinliangnote/go-gin-api/blob/master/LICENSE
  title: swagger 接口文档
  version: "2.0"
paths:
  /auth/get:
    post:
      consumes:
      - application/json
      description: 获取授权信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/demo.authResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 获取授权信息
      tags:
      - Demo
  /demo/trace:
    get:
      consumes:
      - application/json
      description: Trace 示例
      parameters:
      - description: 签名
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              properties:
                job:
                  description: 工作
                  type: string
                name:
                  description: 用户名
                  type: string
              type: object
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/code.Failure'
      summary: Trace 示例
      tags:
      - Demo
  /user/create:
    post:
      consumes:
      - application/json
      description: 创建用户
      parameters:
      - description: 请求信息
        in: body
        name: RequestInfo
        required: true
        schema:
          $ref: '#/definitions/user_model.CreateRequest'
      - description: 签名
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_model.CreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 创建用户
      tags:
      - User
  /user/delete/{id}:
    patch:
      consumes:
      - application/json
      description: 删除用户 - 更新 is_deleted = 1
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 签名
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 删除用户 - 更新 is_deleted = 1
      tags:
      - User
  /user/info/{username}:
    get:
      consumes:
      - application/json
      description: 用户详情
      parameters:
      - description: 用户名
        in: path
        name: username
        required: true
        type: string
      - description: 签名
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_model.DetailResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 用户详情
      tags:
      - User
  /user/update:
    put:
      consumes:
      - application/json
      description: 编辑用户 - 通过用户主键ID更新用户昵称
      parameters:
      - description: 请求信息
        in: body
        name: RequestInfo
        required: true
        schema:
          $ref: '#/definitions/user_model.UpdateNickNameByIDRequest'
      - description: 签名
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_model.UpdateNickNameByIDResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/code.Failure'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/code.Failure'
      summary: 编辑用户 - 通过用户主键ID更新用户昵称
      tags:
      - User
swagger: "2.0"
