host: localhost:9999
info:
  contact: {}
  title: go-gin-api docs api
paths:
  /demo/user/{name}:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      parameters:
      - description: 用户名
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户信息
          schema:
            items:
              properties:
                job:
                  description: 工作
                  type: string
                name:
                  description: 用户名
                  type: string
              type: object
            type: array
      summary: 获取用户信息
      tags:
      - Demo
swagger: "2.0"
